### ISSUE TITLE
Ubisoft server error when using a custom IDTABLE

### ISSUE THREAD

**Issue by WodsonKun** [wukko/ubiart-id-table#1]
Hi!

![image](https://user-images.githubusercontent.com/22161127/177055804-16a7c221-2d3b-4249-9a16-d26eecd955d0.png)
I ran onto this error when using your IDT tool, the game boots fine and even goes to song selection
But when I try to play a song, it throws this error and sends me back to the title screen

Thanks in advance!

**Comment by wukko** [comment]
ubisoft server error occurs when there's something wrong with media content such as .webm video or audio file

**Comment by wukko** [comment]
if there was something wrong with id table, map would be marked as "not installed"

**Comment by WodsonKun** [comment]
Yeah, I ended up figuring out the issue by my own and yeah, it was a missing "world" folder
Idk why, as I was sure that I added it, but well, happens
That's why I closed the issue

Thanks for answering, tho ❤️
