### ISSUE TITLE
Still saying "Installing" after using the tool

### ISSUE THREAD

**Issue by JustAsierOfi** [wukko/ubiart-id-table#2]

**Comment by wukko** [comment]
i need more details

1. what's the bundle name you used?
2. does map square appear in game menu?
3. are you sure that map bundle itself is correct and should load?

**Comment by JustAsierOfi** [comment]
1- dance_pc.ipk
2- Yes
3- Yeah the map loads when I name bundle_0.ipk

**Comment by WodsonKun** [comment]
If i'm not wrong, the bundle needs to be compatible with the IDTABLE
Something like that, i'm not sure

I tried using Eliott and Augusto's bundle generators, but only Eliott's worked with the IDTABLE (And it's not a 100% thing... my bboombboom_pc.ipk worked fine, but my sogood_pc.ipk didn't)

**Comment by wukko** [comment]
you could try making a separate folder for maps in game directory and re-running the script

it'd also be nice if you could give me a list of ipk files and generated idtable that doesn't work

**Comment by WodsonKun** [comment]
![image](https://user-images.githubusercontent.com/22161127/177472684-5722c69a-3fb7-4cae-bd8d-83b007f484f3.png)

Putting bundles inside of a different folder worked, this was generated using Augusto's bundle generator

**Comment by JustAsierOfi** [comment]
You mean putting the custom songs ipks into a different folder of the main ipks
![Captura de pantalla 2022-07-06 132619](https://user-images.githubusercontent.com/104210214/177539813-c2955bec-7025-463e-91a9-4c135d90c62a.png) Like this??

**Comment by wukko** [comment]
i dont think it'd work with spaces

**Comment by JustAsierOfi** [comment]
I've tried and only works in 1 song of 4 that I added. All the songs are created with Augusto Bundle Generator

**Comment by WodsonKun** [comment]
@JustAsierOfi I created a "maps" folder, instead of "Custom Bundles"
I created 5 bundles and all of them worked, still using Augusto's bundle generator

**Comment by JustAsierOfi** [comment]
Yeah I fix it creating a folder called maps
